# Generated by Django 5.2 on 2025-04-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('dorsal', models.PositiveIntegerField()),
                ('posicion', models.CharField(choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('MED', 'Centrocampista'), ('DEL', 'Delantero')], max_length=3)),
                ('foto', models.ImageField(upload_to='jugadores/')),
                ('lugar_nacimiento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('bandera', models.ImageField(upload_to='banderas/')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pie_preferido', models.CharField(max_length=10)),
                ('fin_contrato', models.DateField()),
            ],
        ),
    ]
