# Generated by Django 5.2 on 2025-04-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
