# Generated by Django 5.2 on 2025-04-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jugador_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rival', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('estadio', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_rival', models.ImageField(blank=True, null=True, upload_to='logos_rivales/')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
