# Generated by Django 5.2 on 2025-04-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_usuario_comentario_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='jornada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
