# Generated by Django 5.2 on 2025-04-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_partido_jornada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='rival',
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo_local',
            field=models.CharField(default='Equipo Local Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo_visitante',
            field=models.CharField(default='Equipo Visitante Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_local',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_visitante',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='temporada',
            field=models.CharField(default='2024-2025', max_length=10),
        ),
    ]
