# Generated by Django 5.2 on 2025-04-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_partido_rival_partido_equipo_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='logo_local',
            field=models.ImageField(blank=True, null=True, upload_to='logos_locales/'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_local',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_visitante',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
