# Generated by Django 5.2 on 2025-04-25 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_partido_logo_local_alter_partido_goles_local_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='partido',
            options={},
        ),
        migrations.RemoveField(
            model_name='partido',
            name='logo_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='logo_rival',
        ),
        migrations.AlterField(
            model_name='partido',
            name='estadio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_local',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_visitante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='jornada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='temporada',
            field=models.CharField(default='2024-2025', max_length=9),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='core.equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='core.equipo'),
        ),
    ]
