# Generated by Django 5.2 on 2025-04-25 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_equipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partido',
            options={},
        ),
        migrations.RemoveField(
            model_name='partido',
            name='logo_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='logo_rival',
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='core.equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='core.equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='estadio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_local',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_visitante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='jornada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='temporada',
            field=models.CharField(default='2024-2025', max_length=9),
        ),
    ]
